/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityRecord {
  'id' : bigint,
  'inputData' : string,
  'action' : string,
  'isFavorite' : boolean,
  'outputData' : string,
  'timestamp' : Time,
}
export interface ChatMessage {
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export type RequestStatus = { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export type Time = bigint;
export interface TransportRequest {
  'status' : RequestStatus,
  'scheduledTime' : Time,
  'estimatedPrice' : bigint,
  'dropLocation' : string,
  'timestamp' : Time,
  'cropType' : string,
  'driver' : [] | [Principal],
  'farmer' : Principal,
  'quantityKg' : bigint,
  'pickupLocation' : string,
}
export interface UserProfile { 'displayName' : string, 'role' : UserRole }
export type UserRole = { 'driver' : null } |
  { 'farmer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'clearAllActivities' : ActorMethod<[], undefined>,
  'createTransportRequest' : ActorMethod<
    [string, bigint, string, string, Time],
    bigint
  >,
  'deleteActivity' : ActorMethod<[bigint], undefined>,
  'deleteRequest' : ActorMethod<[bigint], undefined>,
  'getAllRequests' : ActorMethod<[], Array<TransportRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMyActivities' : ActorMethod<[], Array<ActivityRecord>>,
  'getMyRequests' : ActorMethod<[], Array<TransportRequest>>,
  'getStats' : ActorMethod<
    [],
    {
      'totalDrivers' : bigint,
      'totalDelivered' : bigint,
      'totalRequests' : bigint,
      'totalFarmers' : bigint,
    }
  >,
  'getTransportRequest' : ActorMethod<[bigint], TransportRequest>,
  'getUserCreatedAt' : ActorMethod<[], Time>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logActivity' : ActorMethod<[string, string, string], undefined>,
  'registerUser' : ActorMethod<[string, UserRole], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], undefined>,
  'switchRole' : ActorMethod<[UserRole], undefined>,
  'toggleFavorite' : ActorMethod<[bigint], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateRequestStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];