/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const TransportRequest = IDL.Record({
  'status' : RequestStatus,
  'scheduledTime' : Time,
  'estimatedPrice' : IDL.Nat,
  'dropLocation' : IDL.Text,
  'timestamp' : Time,
  'cropType' : IDL.Text,
  'driver' : IDL.Opt(IDL.Principal),
  'farmer' : IDL.Principal,
  'quantityKg' : IDL.Nat,
  'pickupLocation' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'driver' : IDL.Null,
  'farmer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'role' : UserRole,
});
export const ChatMessage = IDL.Record({
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createTransportRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
  'getAllRequests' : IDL.Func([], [IDL.Vec(TransportRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(TransportRequest)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalDrivers' : IDL.Nat,
          'totalDelivered' : IDL.Nat,
          'totalRequests' : IDL.Nat,
          'totalFarmers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTransportRequest' : IDL.Func([IDL.Nat], [TransportRequest], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, UserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'switchRole' : IDL.Func([UserRole], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const TransportRequest = IDL.Record({
    'status' : RequestStatus,
    'scheduledTime' : Time,
    'estimatedPrice' : IDL.Nat,
    'dropLocation' : IDL.Text,
    'timestamp' : Time,
    'cropType' : IDL.Text,
    'driver' : IDL.Opt(IDL.Principal),
    'farmer' : IDL.Principal,
    'quantityKg' : IDL.Nat,
    'pickupLocation' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'driver' : IDL.Null, 'farmer' : IDL.Null });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'role' : UserRole,
  });
  const ChatMessage = IDL.Record({
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createTransportRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(TransportRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(TransportRequest)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalDrivers' : IDL.Nat,
            'totalDelivered' : IDL.Nat,
            'totalRequests' : IDL.Nat,
            'totalFarmers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTransportRequest' : IDL.Func([IDL.Nat], [TransportRequest], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, UserRole], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'switchRole' : IDL.Func([UserRole], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };